### ISSUE TITLE
Spell check doesn't work on web browser discord client

### ISSUE THREAD

**Issue by talregev** [discord/discord-example-app#1]
My spell check work on all other pages except discord chat msgs. 
I am using chrome 100 with windows 11.
Can you make the spell check work along your web client? 
Bug:
![bug](https://user-images.githubusercontent.com/7043539/162561401-1e3b59a1-d45c-44a0-88f1-e48449f5986d.png)

Good example from my report: 
![good_example](https://user-images.githubusercontent.com/7043539/162561418-c2f4bdf7-f222-4a51-94fb-3bcf0d6f1704.png)

**Comment by ThatSkyz** [comment]
This repo is not for client issues, you should submit those to support at the following link: https://dis.gd/bugreport

**Comment by talregev** [comment]
I already report to them. Can you leave it open for other, that have similar issue, and will not report again to bugreport?

**Comment by shaydewael** [comment]
As Skyz said, this repo isn't for Discord client issues and is better served by support so I'm going to close this out.
