### ISSUE TITLE
Getting "Bad request signature" error while setting up interations endpoint URL

### ISSUE THREAD

**Issue by Arjun021** [discord/discord-example-app#20]
After running the example and running local server with **ngrok** . I set the URL in discord settings according to the doc but after that I am getting **Bad request signature** error. 

<img width="876" alt="image" src="https://user-images.githubusercontent.com/90953201/216832674-22db23a0-6a9f-4d8d-8bef-7b90d074d11b.png">

It's coming from the utils.js file `VerifyDiscordRequest` function. How can we resolve this issue ?

**Comment by jaku** [comment]
You need to make sure the URL you're saving on Discord has /interactions at the end.

So don't just post https://asdfasdfasdfasd.ngrok.io, make sure it's https://asdfasdfasdfasd.ngrok.io/interactions

**Comment by kvn-prhn** [comment]
I'm getting a similar error message. I added `/interactions` on the end of my ngrok url I put in the discord endpoint url app setting.
```
Error: Bad request signature
    at <path>/discord-example-app/utils.js:13:13
    at <path>\discord-example-app\node_modules\body-parser\lib\read.js:111:9
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (<path>\discord-example-app\node_modules\raw-body\index.js:231:16)
    at done (<path>\discord-example-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (<path>\discord-example-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by kvn-prhn** [comment]
Turns out my problem was that I copied the wrong token into `DISCORD_TOKEN` in `.env`. Once I copied the right thing it worked.

**Comment by tflagg** [comment]
I am currently experiencing this problem, where did you find the correct token? It provided me with one, which I assumed was the right one...but perhaps not.

**Comment by lajawi** [comment]
> Turns out my problem was that I copied the wrong token into `DISCORD_TOKEN` in `.env`. Once I copied the right thing it worked.

I have a similar issue, but this doesn't fix it.

**Comment by HaukHuang** [comment]
> > Turns out my problem was that I copied the wrong token into `DISCORD_TOKEN` in `.env`. Once I copied the right thing it worked.
> 
> I have a similar issue, but this doesn't fix it.

Have you already solved this issue?

**Comment by lajawi** [comment]
> > > Turns out my problem was that I copied the wrong token into `DISCORD_TOKEN` in `.env`. Once I copied the right thing it worked.
> > 
> > 
> > I have a similar issue, but this doesn't fix it.
> 
> Have you already solved this issue?

I started from scratch, so in a way, yes, but I didn't solve the issue itself.

**Comment by uchijo** [comment]
In my case, .env was not loaded correctly.
I'm not sure it helps you, but here's my situation:

I was running app on docker compose, since I wanted to use it with cloudflare tunnel.
Here's part of my docker-compose.yml, which **did not work correctly**:

```docker-compose.yml
version: '3.1'

services:
  app:
    image: node:latest
    command: node /app/app.js # this is not good. this way of invoking app.js won't load .env in the project root.
    volumes:
      - ./:/app/
  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
...
```

as written in comment, the way starting the server was not good.
and this is the config which worked correctly:

```docker-compose.yml
version: '3.1'

services:
  app:
    image: node:latest
    working_dir: /app
    command: node app.js
    volumes:
      - ./:/app/
  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
...
```

Hope this helps someone :)

**Comment by LK00100100** [comment]
I have problems connecting to the INTERACTIONS ENDPOINT URL.

These didn't work for me (and I used the debugger to check the values)
- this current repo's code `const isValidRequest = verifyKey(req.rawBody, signature, timestamp, 'MY_CLIENT_PUBLIC_KEY');`
- using `import nacl from 'tweetnacl'; nacl.sign.detached.verify(xxx)` from https://discord.com/developers/docs/interactions/receiving-and-responding#security-and-authorization


What worked was this:
```
import { verifyKeyMiddleware } from 'discord-interactions';
app.post('/interactions', verifyKeyMiddleware(process.env.PUBLIC_KEY), async function (req, res) {
```

**Comment by JustinBeckwith** [comment]
Greetings folks!  The code sample has been updated to use `verifyKeyMiddleware`, which solve one class of problems brought up here.  For others, please open a new issue if you're still running into trouble :)
