### ISSUE TITLE
Examples : InteractionResponseType.MODAL instead of InterationResponseType.APPLICATION_MODAL

### ISSUE THREAD

**Issue by yannisroy** [discord/discord-example-app#21]
I was struggling using modal interactions and getting "Interaction failed" errors.

Exemple here does not match correct response type : 
https://github.com/discord/discord-example-app/blob/main/examples/modal.js#L25

Solved when using `InteractionResponseType.MODAL`

**Comment by Hattman** [comment]
similar issue for the submit as well, https://github.com/discord/discord-example-app/blob/main/examples/modal.js#L64
changing it to InteractionType.MODAL_SUBMIT fixes the issue.
