### ISSUE TITLE
Discord does not seem to handle interactions properly.

### ISSUE THREAD

**Issue by Slace31** [discord/discord-example-app#34]
Hi.
I'm trying the getting started guide from discord dev portal and I have a weird behavior.
When I use the /test command on discord everything looks good on ngrok and in my terminal but no message is shown in the discord channel.
![image](https://github.com/discord/discord-example-app/assets/15848235/ea812346-63e1-4b4a-9e69-6bf6be325c46)
![image](https://github.com/discord/discord-example-app/assets/15848235/36e9b95c-7f67-4fcb-a125-736df37943b3)
![image](https://github.com/discord/discord-example-app/assets/15848235/729fb6d5-0dd0-4ad9-8402-2738b1f11806)
![image](https://github.com/discord/discord-example-app/assets/15848235/8a1edce7-2c44-4213-8530-eb795e0aef3f)

Am I the only one ?

**Comment by momuno** [comment]
I am using Glitch, and experiencing something very similar.  No "hello world + emoji" appears in the channel.

**Comment by Slace31** [comment]
Ok I found out what was the error, my bot had "discord" in his name and it seems discord didn't like it.
I'm closing this issue.
