### ISSUE TITLE
Feature Request: Friend Invite Link

### ISSUE THREAD

**Issue by BrotherRabbit91** [discord/discord-example-app#58]
Hello Discord Team,

I hope this message finds you well. I would like to propose a feature that I believe would enhance the user experience on Discord: the ability to create a direct invite link for adding friends.

Currently, users can only send friend requests by entering usernames and discriminators. Introducing a feature that allows users to generate a unique invite link to share with friends would simplify the process and make it more accessible, especially for those who may not know how to find someone’s username or are new to the platform.

This feature could work similarly to how server invites function, allowing users to share a link that, when clicked, would automatically send a friend request to the user associated with that link.

**Comment by JustinBeckwith** [comment]
Greetings!  This repository is for tracking issues and features with our API getting started sample.  For general feature requests or bugs, please see https://support.discord.com/hc/en-us/articles/213490807-Where-can-I-submit-Feature-Requests-Feedback-and-Suggestions

**Comment by BrotherRabbit91** [comment]
Thanks, @JustinBeckwith
