### ISSUE TITLE
  la página [] </Error> https://discord.com/new/terms

### ISSUE THREAD

**Issue by Daniela9696** [discord/discord-example-app#60]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).</Details>

**Comment by JustinBeckwith** [comment]
Greetings!  It's unclear what this issue has to do with the repository.
