### ISSUE TITLE
ngrok validation error

### ISSUE THREAD

**Issue by 4irelabs-kostiantyn** [discord/discord-example-app#8]
Failed to register ngRok URL when trying to follow instructions. I always get the same validation error:
`{"code": 50035, "errors": {"interactions_endpoint_url": {"_errors": [{"code": "APPLICATION_INTERACTIONS_ENDPOINT_URL_INVALID", "message": "The specified interactions endpoint URL could not be verified."}]}}, "message": "Invalid Form Body"}`

**Comment by intair** [comment]
You closed this, what was the fix? was working last night for me and now it just doesnt.

**Comment by slingercode** [comment]
> You closed this, what was the fix? was working last night for me and now it just doesnt.

[Here is the solution](https://github.com/discord/discord-example-app/issues/16#issuecomment-1321362852)
